[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "condastats"
dynamic = ["version"]
description = "Conda package stats CLI"
readme = "README.rst"
license = {text = "BSD license"}
authors = [
    {name = "Sophia Man Yang"}
]
keywords = ["condastats"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.16.5,<2.0.0",
    "pandas>=1.5.0,<2.0.0",
    "dask[dataframe]>=2023.1.0,<2024.3.0",
    "pyarrow>=10.0.0,<15.0.0",
    "s3fs>=2023.1.0",
    "python-snappy",
]

[project.optional-dependencies]
test = ["pytest"]

[project.scripts]
condastats = "condastats.cli:main"

[project.urls]
Homepage = "https://github.com/sophiamyang/condastats"

[tool.setuptools]
packages = ["condastats"]

[tool.setuptools_scm]
