name: Tests

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.os == 'windows-latest' && 'pwsh' || 'bash -el {0}' }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    timeout-minutes: 30
    env:
      CACHE_NUMBER: 0  # Increase to reset cache
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
          activate-environment: test-env
          channels: conda-forge
          channel-priority: strict
      - name: Get cache date
        id: get-date
        shell: bash
        run: echo "today=$(/bin/date -u '+%Y%W')" >> $GITHUB_OUTPUT
      - name: Cache conda env
        uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-${{ runner.os }}-${{ runner.arch }}-py${{ matrix.python-version }}-${{ steps.get-date.outputs.today }}-${{ env.CACHE_NUMBER }}
        id: cache
      - name: Enable sharded repodata
        run: |
          conda install -n base -y "conda-libmamba-solver>=25.11.0"
          conda config --set plugins.use_sharded_repodata true
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          conda install -y "numpy>=1.20.0" "pandas>=2.0.0" "dask>=2024.5.2" "pyarrow>=10.0.0" "s3fs>=2023.1.0" python-snappy pytest pytest-cov
      - name: Install package
        run: pip install -e . --no-deps
      - name: PyTest
        run: pytest -v --cov=condastats --cov-report=term-missing
